apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: diaggarw
    labels:
        app: diaggarw
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: diaggarwbaac-diaggarw.8fd377fc1d604524b4e1.southindia.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: diaggarw
                servicePort: 80