on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n diaggarwAcr -g diaggarwAcr996b-rg --location "South India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n diaggarwAcr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n diaggarwAcr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n diaggarwAcr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t diaggarwacr.azurecr.io/diaggarw:${{ github.sha }}
        docker push diaggarwacr.azurecr.io/diaggarw:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_diaggarw_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarw7f07 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarw7f07`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarw7f07
        container-registry-url: diaggarwacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: diaggarwdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarw7f07
        manifests: |
          manifests/deployment-30.yml
          manifests/service-30.yml
        images: |
          diaggarwacr.azurecr.io/diaggarw:${{ github.sha }}
        imagepullsecrets: |
          diaggarwdockerauth