on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bishalcontainer1acr.azurecr.io
        username: ${{ secrets.acr_bishalcontainer1acr_username }}
        password: ${{ secrets.acr_bishalcontainer1acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t bishalcontainer1acr.azurecr.io/vipulakscluster:${{ github.sha }}
        docker push bishalcontainer1acr.azurecr.io/vipulakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulakscluster1cfd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulakscluster1cfd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulakscluster1cfd
        container-registry-url: bishalcontainer1acr.azurecr.io
        container-registry-username: ${{ secrets.acr_bishalcontainer1acr_username }}
        container-registry-password: ${{ secrets.acr_bishalcontainer1acr_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulakscluster1cfd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          bishalcontainer1acr.azurecr.io/vipulakscluster:${{ github.sha }}
        imagepullsecrets: |
          vipulaksclusdockerauth