on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwregistry.azurecr.io
        username: ${{secrets.acr_diaggarwRegistry_username}}
        password: ${{secrets.acr_diaggarwRegistry_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t diaggarwregistry.azurecr.io/diaggarw4949:${{github.sha}}
        docker push diaggarwregistry.azurecr.io/diaggarw4949:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_diaggarw_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarw6066 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarw6066`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarw6066
        container-registry-url: diaggarwregistry.azurecr.io
        container-registry-username: ${{secrets.acr_diaggarwRegistry_username}}
        container-registry-password: ${{secrets.acr_diaggarwRegistry_password}}
        secret-name: diaggarwdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarw6066
        manifests: |
          manifests/deployment-966b.yml
          manifests/service-966b.yml
        images: |
          diaggarwregistry.azurecr.io/diaggarw4949:${{github.sha}}
        imagepullsecrets: |
          diaggarwdockerauth