on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: diaggarw.azurecr.io
        username: ${{ secrets.acr_diaggarw_username }}
        password: ${{ secrets.acr_diaggarw_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t diaggarw.azurecr.io/diaggarwtest:${{ github.sha }}
        docker push diaggarw.azurecr.io/diaggarwtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_diaggarwtest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarwtestf72c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarwtestf72c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarwtestf72c
        container-registry-url: diaggarw.azurecr.io
        container-registry-username: ${{ secrets.acr_diaggarw_username }}
        container-registry-password: ${{ secrets.acr_diaggarw_password }}
        secret-name: diaggarwtestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarwtestf72c
        manifests: |
          manifests/deployment-21.yml
          manifests/service-21.yml
        images: |
          diaggarw.azurecr.io/diaggarwtest:${{ github.sha }}
        imagepullsecrets: |
          diaggarwtestdockerauth